# Generated by Django 2.2.4 on 2021-06-03 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descreption',
            new_name='description',
        ),
    ]
