# Generated by Django 2.2.4 on 2021-06-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210603_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_creator',
        ),
    ]
