# Generated by Django 2.2.4 on 2021-06-03 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210603_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
