# Generated by Django 2.2.4 on 2021-06-05 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
