# Generated by Django 2.2.4 on 2021-06-06 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_event_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='attended_by',
            field=models.ManyToManyField(related_name='attended_events', to='events.Users'),
        ),
    ]
