# Generated by Django 2.2.4 on 2021-06-06 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_auto_20210606_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
